/* NOVA enhancement layer: themes, custom apps and direct realtime chat */
(function(){
const T={midnight:["Midnight","#a78bfa","#07070a"],ocean:["Ocean","#38bdf8","#061016"],rose:["Rose","#fb7185","#10070b"],aurora:["Aurora","#34d399","#06100c"],sunset:["Sunset","#fb923c","#100a05"],mono:["Mono","#e5e7eb","#080808"]};
const I=n=>"https://api.iconify.design/lucide:"+n+".svg?color=%23ffffff";
const built=[["NOVA AI","Assistant & workspace","sparkles","ai"],["Games","Play & save scores","gamepad-2","games"],["Social","Feed & live chat","users","social"],["Create","Build saved projects","wand-2","create"],["Market","Discover drops","shopping-bag","market"],["Mystery","Puzzles & secrets","scan-search","mystery"]];
const esc2=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const safe=u=>{try{let x=new URL(u);return /^https?:$/.test(x.protocol)?x.href:""}catch{return""}};
function setTheme(){let t=T[profile?.theme]||T.midnight;document.documentElement.style.setProperty("--accent",profile?.accent_color||t[1]);document.documentElement.style.setProperty("--bg",t[2])}
function modal(h){let m=document.getElementById("modal");if(!m){m=document.createElement("div");m.id="modal";m.className="modal";document.body.appendChild(m)}m.innerHTML='<div class="sheet">'+h+"</div>";m.classList.add("show")}
function close(){document.getElementById("modal")?.classList.remove("show")}
function icon(u){return '<img src="'+esc2(u)+'" alt="">'}
window.novaThemes=T;
window.novaAddApp=function(){modal('<div class="tag">ADD YOUR OWN APP</div><h2>Create an app shortcut</h2><p class="muted">Add any HTTPS website to your NOVA app library.</p><input id="appName" class="input" placeholder="App name"><input id="appDesc" class="input" placeholder="Description"><input id="appUrl" class="input" placeholder="https://example.com"><input id="appIcon" class="input" placeholder="Icon image URL (optional)"><button class="btn full" onclick="novaCreateApp()">Add app</button><button class="btn dark full" onclick="novaClose()">Cancel</button>')}
window.novaClose=close;
window.novaCreateApp=async function(){let name=document.getElementById("appName").value.trim(),description=document.getElementById("appDesc").value.trim(),url=safe(document.getElementById("appUrl").value.trim()),iconUrl=safe(document.getElementById("appIcon").value.trim());if(!name||!url)return toast("Enter a name and valid URL");let r=await sb.from("apps").insert({name,description,launch_url:url,icon_url:iconUrl,created_by:session.user.id}).select("id").single();if(r.error)return toast(r.error.message);let u=await sb.from("user_apps").insert({user_id:session.user.id,app_id:r.data.id});if(u.error)return toast(u.error.message);close();toast("App added");render()};
window.novaLaunch=function(u){let x=safe(u);if(x)window.open(x,"_blank","noopener,noreferrer");else toast("Invalid app URL")};
window.novaSaveTheme=async function(name){let t=T[name],r=await sb.from("profiles").update({theme:name,accent_color:t[1],updated_at:new Date().toISOString()}).eq("id",session.user.id);if(r.error)return toast(r.error.message);profile.theme=name;profile.accent_color=t[1];setTheme();close();render()};
window.novaChat=async function(id,name){let q=await sb.from("messages").select("*").or("and(sender_id.eq."+session.user.id+",recipient_id.eq."+id+"),and(sender_id.eq."+id+",recipient_id.eq."+session.user.id+")").order("created_at");modal('<div class="tag">DIRECT MESSAGE</div><h2>'+esc2(name)+'</h2><div id="novaChatBox" style="height:45dvh;overflow:auto;padding:8px 0"></div><input id="novaChatInput" class="input" placeholder="Message..."><button class="btn full" onclick="novaSendChat(\''+id+'\')">Send</button><button class="btn dark full" onclick="novaCloseChat()">Close</button>');let box=document.getElementById("novaChatBox");(q.data||[]).forEach(m=>novaAppend(m));window._novaChat={id};let ch=sb.channel("dm-"+session.user.id+"-"+id);ch.on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},p=>{let m=p.new;if((m.sender_id===session.user.id&&m.recipient_id===id)||(m.sender_id===id&&m.recipient_id===session.user.id))novaAppend(m)}).subscribe();window._novaChat.channel=ch;setTimeout(()=>{box.scrollTop=box.scrollHeight},30)};
function novaAppend(m){let b=document.getElementById("novaChatBox");if(!b)return;let d=document.createElement("div");d.style.cssText="max-width:78%;padding:10px 13px;margin:7px 0;border-radius:16px;background:"+(m.sender_id===session.user.id?"var(--accent)":"#1a1a21")+";color:"+(m.sender_id===session.user.id?"#08080a":"#fff")+";margin-left:"+(m.sender_id===session.user.id?"auto":"0");d.textContent=m.content;b.appendChild(d);b.scrollTop=b.scrollHeight}
window.novaSendChat=async function(id){let e=document.getElementById("novaChatInput"),v=e.value.trim();if(!v)return;let r=await sb.from("messages").insert({sender_id:session.user.id,recipient_id:id,content:v});if(r.error)toast(r.error.message);else e.value=""};
window.novaCloseChat=function(){if(window._novaChat?.channel)sb.removeChannel(window._novaChat.channel);window._novaChat=null;close()};
window.novaSettings=function(){setTheme();let rows=Object.entries(T).map(([k,t])=>'<button class="theme" onclick="novaSaveTheme(\''+k+'\')"><div style="height:40px;border-radius:10px;background:linear-gradient(135deg,'+t[1]+','+t[2]+')"></div><b>'+t[0]+"</b></button>").join("");document.getElementById("root").innerHTML='<div class="screen"><div class="eyebrow">NOVA / SETTINGS</div><h1>Settings</h1><p class="muted">Themes are saved to your NOVA profile.</p><div class="theme-row">'+rows+'</div><div class="card" style="margin-top:14px"><h3>Account</h3><p class="muted">'+esc2(session.user.email)+"</p></div><button class="btn dark full" onclick="sb.auth.signOut()">Sign out</button><button class="btn full" onclick="go('home')">Back</button></div>"};
window.novaApps=async function(){let r=await sb.from("user_apps").select("app_id,apps(id,name,description,icon_url,launch_url)").eq("user_id",session.user.id).order("position"),custom=(r.data||[]).map(x=>x.apps).filter(Boolean);let builtHtml=built.map(a=>'<div class="card module" onclick="go(\''+a[3]+'\')"><div class="icon">'+icon(I(a[2]))+'</div><h3>'+a[0]+'</h3><p>'+a[1]+"</p></div>").join("");let own=custom.map(a=>'<div class="card module" onclick="novaLaunch(\''+esc2(a.launch_url||"")+'\')"><div class="icon">'+icon(a.icon_url||I("app-window"))+'</div><h3>'+esc2(a.name)+'</h3><p>'+esc2(a.description||"Custom app")+"</p></div>").join("");document.getElementById("root").innerHTML='<div class="screen"><div class="eyebrow">NOVA / APPS</div><div class="top"><div><h1>App Library</h1><p class="muted">Your built-in and custom apps.</p></div><button class="btn dark" style="margin:0" onclick="novaAddApp()">＋ Add</button></div><div class="section"><h2>Built in</h2></div><div class="grid">'+builtHtml+'</div><div class="section"><h2>Your apps</h2></div><div class="grid">'+(own||'<div class="card"><p class="muted">No custom apps yet.</p></div>')+'</div></div>'+nav()};
const oldRender=window.render;
window.render=async function(){setTheme();return oldRender()};
window.go=window.go;
const originalSettings=window.settings;window.settings=function(){novaSettings()};
const originalNav=window.nav;window.nav=function(){return '<nav class="nav">'+[["home","⌂","Home"],["apps","▦","Apps"],["social","◎","Chat"],["create","＋","Create"],["settings","⚙","Settings"]].map(x=>'<button class="'+(tab===x[0]?"active":"")+'" onclick="go(\''+x[0]+'\')"><b>'+x[1]+'</b><span>'+x[2]+"</span></button>").join("")+"</nav>"};
const originalSocial=window.social;window.social=async function(){let r=await sb.from("profiles").select("id,username,display_name,avatar_url").neq("id",session.user.id).limit(30);return '<div class="screen"><div class="eyebrow">NOVA / CHAT</div><h1>Chat</h1><p class="muted">Direct messages update instantly.</p>'+((r.data||[]).length?(r.data||[]).map(u=>'<div class="card tool" onclick="novaChat(\''+u.id+'\',\''+esc2(u.display_name||u.username||"NOVA user")+'\')"><div class="avatar">'+(u.avatar_url?'<img src="'+esc2(u.avatar_url)+'">':esc2((u.display_name||u.username||"N").slice(0,1).toUpperCase()))+'</div><div class="grow"><h3>'+esc2(u.display_name||u.username||"NOVA user")+'</h3><p>@'+esc2(u.username||"user")+"</p></div><span>›</span></div>").join(""):'<div class="card"><p class="muted">No other users yet. Create another NOVA account to test live chat.</p></div>')+'</div>'+nav()};
const originalMystery=window.mystery;window.mystery=originalMystery;
const originalMarket=window.market;window.market=originalMarket;
const baseRender=window.render;
window.render=async function(){if(!session){return baseRender()}setTheme();if(tab==="apps"){return novaApps()}if(tab==="settings"){return novaSettings()}if(tab==="social"){let h=await window.social();document.getElementById("root").innerHTML=h;return}return baseRender()};
setTheme();
if(session)window.render();
})();
